### ISSUE TITLE
Take equal values into account in frequency_comparison function

### ISSUE THREAD

**Issue by mackenzieyoung** [R037/Murder-Mystery#1]
Right now, your frequency comparison function doesn't account for when the two values are equal. To fix this, instead of passing in your else statement, do this:

```
            else:
                appearances += table2[key]
                mutual_appearances += table1[key] 
``` 

When you test your function, you should get an output of 1.0 when the two frequency tables are identical.

**Comment by R037** [comment]
Fixed by:
elif table2[key]>=table1[key]:
                appearances += table2[key]
                mutual_appearances += table1[key]
